export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const CHANGE_SEARCH_STR = 'CHANGE_SEARCH_STR';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';
export const CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY';
